# run test suite
---
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git commit
        uses: actions/checkout@v3

      - name: Run tests
        env:
          # Use docker-compose testing override, to stop before production stage
          COMPOSE_FILE: docker-compose.yaml:docker-compose.test.yaml
        run: "
          docker-compose run --rm client
            yarn test
        "
